In [1]:
import numpy as np

In [2]:
import pandas as pd

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
df=pd.read_csv('/content/drive/MyDrive/cars.csv')

In [6]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [7]:
df.shape

(8128, 5)

In [8]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

### **How many different brands we have?**

In [9]:
df['brand'].nunique()

32

In [10]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [11]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

### **One Hot Encoding using Pandas**

In [12]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

### **K-1 OneHotEncoding**

In [13]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)
# remove first_owner
# remove CNG removed

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

### **In scikit learn we use OneHotEncoding Class**

We dont use pandas in real world module the reason is that it can randomly remove any column not necessarily the first column

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(df[['brand','km_driven','fuel','owner']],df['selling_price'],test_size=0.2,random_state=0)

In [15]:
X_train,X_test

(           brand  km_driven    fuel         owner
 3042     Hyundai      60000     LPG   First Owner
 1520        Tata     150000  Diesel   Third Owner
 2611     Hyundai     110000  Diesel  Second Owner
 3544    Mahindra      28000  Diesel  Second Owner
 4138      Maruti      15000  Petrol   First Owner
 ...          ...        ...     ...           ...
 4931        Tata      70000  Diesel   Third Owner
 3264        Ford     100000  Diesel  Second Owner
 1653     Hyundai      90000  Petrol  Second Owner
 2607  Volkswagen      90000  Diesel   First Owner
 2732     Hyundai     110000  Petrol   First Owner

 [6502 rows x 4 columns],
          brand  km_driven    fuel         owner
 3558   Hyundai      40000  Diesel   First Owner
 233   Mahindra      70000  Diesel   First Owner
 7952    Maruti       5000  Petrol   First Owner
 572     Maruti     120000  Petrol   Third Owner
 6960     Lexus      20000  Petrol   First Owner
 ...        ...        ...     ...           ...
 7576      Fiat     100000  Diesel   Third Owner
 1484    Maruti     120000  Petrol   Third Owner
 1881    Maruti      40000  Diesel   First Owner
 4917   Hyundai       2350  Petrol   First Owner
 5934   Hyundai      80000  Diesel  Second Owner

 [1626 rows x 4 columns])

### **One Hot Encoder**

In [16]:
from sklearn.preprocessing import OneHotEncoder

In [45]:
ohe=OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

You are not gonna apply one hot encoding over every column instead you will apply it on fuel and owner and then after encoding those columns you have to join those columns with older DataFrame

In [46]:
X_train_new=ohe.fit_transform(X_train[['fuel','owner']])

It will produce a sparse matrix having 9 columns because 4 columns are coming from fuel and 5 are coming from owner

In [47]:
ohe.fit_transform(df[['fuel','owner']])

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 0, 1],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [48]:
X_test_new=ohe.transform(X_test[['fuel','owner']])

In [49]:
print(X_train[['brand','km_driven']].values.shape)
print(X_train_new.shape)

(6502, 2)
(6502, 7)

In [51]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Hyundai', 60000, 0, ..., 0, 0, 0],
       ['Tata', 150000, 1, ..., 0, 0, 1],
       ['Hyundai', 110000, 1, ..., 1, 0, 0],
       ...,
       ['Hyundai', 90000, 0, ..., 1, 0, 0],
       ['Volkswagen', 90000, 1, ..., 0, 0, 0],
       ['Hyundai', 110000, 0, ..., 0, 0, 0]], dtype=object)

### **OneHotEncoding with top categories**

In [53]:
counts=df['brand'].value_counts()

In [55]:
df['brand'].nunique()
threshold=100

In [57]:
repl=counts[counts<=threshold].index
repl

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Land', 'Force', 'Isuzu', 'Ambassador',
       'Kia', 'MG', 'Daewoo', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [60]:
pd.get_dummies(df['brand'].replace(repl,'uncommon'))

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
0,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,False,True,False,False,False,False,False,False,False,False
8124,False,False,False,False,True,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,False,True,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,False,True,False,False,False
8127,False,False,False,False,False,False,False,False,False,True,False,False,False